### ISSUE TITLE
approximate place of needle

### ISSUE THREAD

**Issue by MareoRaft** [polovik/Algorithms#2]
The code says
`"""
Return approximately place of needle in haystack and number of alterations.
"""`

Why is the needle place approximate?  Is it impossible to get the exact location?

**Comment by polovik** [comment]
In case of precise matching, the needle place is obvious and "precise". But when the precise matching doesn't work, the fuzzy searching is started. That means, that some part (with several mistakes) of a word from haystack is matching with needle. I thought about this like "approximate" needle position in the word.
